[package]
name = "alator"
version = "0.0.5"
authors = ["Calum Russell <calum.mj.russell@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
time = "0.3.11"
rand = "0.8.4"
rand_distr = "0.4.1"
log = "0.4.17" 
env_logger = "0.9.0"
