[package]
name = "alator"
version = "0.1.0"
authors = ["Calum Russell <calum.mj.russell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
itertools = "0.10.1"
libmath = "0.1.4"
serde = { version = "1.0.117", features = ["derive"] }